language: java
jdk:
  - openjdk11

branches:
  only:
    - deploy
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

notifications:
  email:
    recipients:
      - rhkd1769@gmail.com

