spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:~/celloct;MODE=PostgreSQL;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
