spring:
  profiles:
    group:
      "local": "oauth,local"
      "real": "oauth,real"

  jpa:
    hibernate:
      ddl-auto: none
    #      ddl-auto: create # entity 테스트 상황이므로 create
    properties:
      hibernate:
        format_sql: true # 보기좋게 쿼리 남김
#        show_sql: true # 한줄로 쿼리 보여준다.

logging:
  level:
    org:
      hibernate:
        SQL: debug # 임시로 로그 남김